<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

    <xacro:property name="arm_base_length" value="0.1"></xacro:property>
    <xacro:property name="arm_base_width" value="0.1"></xacro:property>
    <xacro:property name="arm_base_height" value="0.02"></xacro:property>
    <xacro:property name="arm_radius" value="0.02"></xacro:property>
    <xacro:property name="arm_length" value="0.3"></xacro:property>

    <link name="arm_base_link">
        <visual>
            <geometry>
                <box size="${arm_base_length} ${arm_base_width} ${arm_base_height}"></box>
            </geometry>
            <origin xyz="0 0 0" rpy="0 0 0"></origin>
            <material name="orange"></material>
        </visual>
        <collision>
            <geometry>
                <box size="${arm_base_length} ${arm_base_width} ${arm_base_height}"></box>
            </geometry>
            <origin xyz="0 0 0" rpy="0 0 0"></origin>     
        </collision>
        <xacro:box_inertia mass="0.5" length="${2*arm_base_length}" width="${2*arm_base_width}" 
                           height="${2*arm_base_height}" xyz="0 0 0" rpy="0 0 0">
        </xacro:box_inertia>
    </link>

    <link name="forearm_link">
        <visual>
            <geometry>
                <cylinder radius="${arm_radius}" length="${arm_length}"></cylinder>
            </geometry>
            <origin xyz="0 0 ${arm_length/2}" rpy="0 0 0"></origin>
            <material name="yellow"></material>
        </visual>
        <collision>
            <geometry>
                <cylinder radius="${arm_radius}" length="${arm_length}"></cylinder>
            </geometry>
            <origin xyz="0 0 ${arm_length/2}" rpy="0 0 0"></origin>
        </collision>
        <xacro:cylinder_inertia mass="0.3" radius="${2*arm_radius}" length="${2*arm_length}" 
                                xyz="0 0 0" rpy="0 0 0">
        </xacro:cylinder_inertia>         
    </link>

    <link name="hand_link">
        <visual>
            <geometry>
                <cylinder radius="${arm_radius}" length="${arm_length}"></cylinder>
            </geometry>
            <origin xyz="0 0 ${arm_length/2}" rpy="0 0 0"></origin>
            <material name="orange"></material>
        </visual>
        <collision>
            <geometry>
                <cylinder radius="${arm_radius}" length="${arm_length}"></cylinder>
            </geometry>
            <origin xyz="0 0 ${arm_length/2}" rpy="0 0 0"></origin>        
        </collision>
        <xacro:cylinder_inertia mass="0.3" radius="${2*arm_radius}" length="${2*arm_length}" 
                                xyz="0 0 0" rpy="0 0 0">
        </xacro:cylinder_inertia>  
    </link>

    <joint name="arm_base_forearm_joint" type="revolute">
        <parent link="arm_base_link"></parent>
        <child link="forearm_link"></child>
        <limit lower="0" upper="${pi/2.0}" effort="100" velocity="100"></limit>
        <dynamics friction="0.05" damping="0.1"></dynamics>
        <origin xyz="0 0 ${arm_base_height/2}" rpy="0 0 0"></origin>
        <axis xyz="0 1 0"></axis>
    </joint>

    <joint name="forearm_hand_joint" type="revolute">
        <parent link="forearm_link"></parent>
        <child link="hand_link"></child>
        <limit lower="0" upper="${pi/2.0}" effort="100" velocity="100"></limit>
        <dynamics friction="0.05" damping="0.1"></dynamics>
        <origin xyz="0 0 ${arm_length}" rpy="0 0 0"></origin>
        <axis xyz="0 1 0"></axis>
    </joint>

</robot>