<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

    <xacro:property name="camera_length" value="0.01"></xacro:property>
    <xacro:property name="camera_width" value="0.1"></xacro:property>
    <xacro:property name="camera_height" value="0.05"></xacro:property>

    <link name="camera_link">
        <visual>
            <geometry>
                <box size="${camera_length} ${camera_width} ${camera_height}"></box> 
            </geometry>
            <material name="grey"></material>   
        </visual>
        <collision>
            <geometry>
                 <box size="${camera_length} ${camera_width} ${camera_height}"></box> 
            </geometry>
        </collision>
        <xacro:box_inertia mass="0.1" length="${camera_length}" width="${camera_width}" 
                           height="${camera_height}" xyz="0 0 0" rpy="0 0 0"></xacro:box_inertia>
    </link>

    <joint name="base_camera_joint" type="fixed">
        <parent link="base_link"></parent>
        <child link="camera_link"></child>
        <origin xyz="${(base_length+camera_length)/2.0} 0 ${base_height/2} " rpy="0 0 0"></origin>
    </joint>
    
    <gazebo reference="camera_link">
        <material>Gazebo/Red</material>
        <sensor name="camera_sensor" type="camera">
            <pose>0 0 0 0 0 0</pose>
            <visualize>True</visualize>
            <update_rate>10.0</update_rate>
            <plugin name="camera_sensor" filename="libgazebo_ros_camera.so">
                <frame_name>camera_link</frame_name>
            </plugin>
        </sensor>
    </gazebo>

</robot>